# Generated by Django 4.1.3 on 2022-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('job_description', models.TextField()),
            ],
        ),
    ]
